kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  # these labels are deployment related labels
  labels:
    component: nginx
    project: expense
    tier: db
spec:
  replicas: 20
  selector:
    matchLabels:
      component: nginx
      project: expense
      tier: db
  # pod definition
  template:
    metadata:
      labels:
        component: nginx
        project: expense
        tier: db
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
